let
    Origine = Excel.Workbook(File.Contents("C:\Users\Administrator\Downloads\M3S1E2.xlsx"), null, true),
    Ordini_Sheet = Origine{[Item="Ordini",Kind="Sheet"]}[Data],
    #"Intestazioni alzate di livello" = Table.PromoteHeaders(Ordini_Sheet, [PromoteAllScalars=true]),
    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"dqwdqw", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}}),
    #"Rimosse prime righe" = Table.Skip(#"Modificato tipo",2),
    #"Intestazioni alzate di livello1" = Table.PromoteHeaders(#"Rimosse prime righe", [PromoteAllScalars=true]),
    #"Modificato tipo1" = Table.TransformColumnTypes(#"Intestazioni alzate di livello1",{{"COD PROD", type text}, {"Column2", type any}, {"Column3", type any}, {"Collaboratore", type text}, {"Regione", type text}, {"Column6", type date}, {"Categoria", type text}, {"Prodotto", type text}, {"Column9", type any}, {"Prezzo unitario", type number}, {"Quantità", Int64.Type}}),
    #"Rimosse colonne" = Table.RemoveColumns(#"Modificato tipo1",{"Column2", "Column3", "Column9"}),
    #"Rimossi errori" = Table.RemoveRowsWithErrors(#"Rimosse colonne"),
    #"Ordinate righe" = Table.Sort(#"Rimossi errori",{{"Regione", Order.Ascending}}),
    #"Inserito testo troncato" = Table.AddColumn(#"Ordinate righe", "Taglio", each Text.Trim([Regione]), type text),
    #"Inserito testo pulito" = Table.AddColumn(#"Inserito testo troncato", "Pulisci", each Text.Clean([Taglio]), type text),
    #"Rimosse colonne1" = Table.RemoveColumns(#"Inserito testo pulito",{"Taglio"}),
    #"Riordinate colonne" = Table.ReorderColumns(#"Rimosse colonne1",{"COD PROD", "Collaboratore", "Pulisci", "Regione", "Column6", "Categoria", "Prodotto", "Prezzo unitario", "Quantità"}),
    #"Rimosse colonne2" = Table.RemoveColumns(#"Riordinate colonne",{"Regione"}),
    #"Rinominate colonne" = Table.RenameColumns(#"Rimosse colonne2",{{"Pulisci", "Regione"}}),
    #"Sostituito valore" = Table.ReplaceValue(#"Rinominate colonne",null,0,Replacer.ReplaceValue,{"Quantità"}),
    #"Modificato tipo2" = Table.TransformColumnTypes(#"Sostituito valore",{{"Prezzo unitario", Currency.Type}}),
    #"Filtrate righe" = Table.SelectRows(#"Modificato tipo2", each true),
    #"Sostituito valore1" = Table.ReplaceValue(#"Filtrate righe","  Jack","Jack",Replacer.ReplaceText,{"Prodotto"}),
    #"Filtrate righe1" = Table.SelectRows(#"Sostituito valore1", each true),
    #"Sostituito valore2" = Table.ReplaceValue(#"Filtrate righe1","Jack ","Jack",Replacer.ReplaceText,{"Prodotto"}),
    #"Inserito testo pulito1" = Table.AddColumn(#"Sostituito valore2", "Pulisci", each Text.Clean([Prodotto]), type text),
    #"Inserito testo troncato1" = Table.AddColumn(#"Inserito testo pulito1", "Taglio", each Text.Trim([Pulisci]), type text),
    #"Filtrate righe2" = Table.SelectRows(#"Inserito testo troncato1", each true),
    #"Rimosse colonne3" = Table.RemoveColumns(#"Filtrate righe2",{"Pulisci"}),
    #"Riordinate colonne1" = Table.ReorderColumns(#"Rimosse colonne3",{"COD PROD", "Collaboratore", "Regione", "Column6", "Categoria", "Taglio", "Prodotto", "Prezzo unitario", "Quantità"}),
    #"Rimosse colonne4" = Table.RemoveColumns(#"Riordinate colonne1",{"Prodotto"}),
    #"Rinominate colonne1" = Table.RenameColumns(#"Rimosse colonne4",{{"Taglio", "Prodotto"}}),
    #"Inserito testo troncato2" = Table.AddColumn(#"Rinominate colonne1", "Taglio", each Text.Trim([Categoria]), type text),
    #"Rimosse colonne5" = Table.RemoveColumns(#"Inserito testo troncato2",{"Categoria"}),
    #"Rinominate colonne2" = Table.RenameColumns(#"Rimosse colonne5",{{"Taglio", "Categoria"}}),
    #"Riordinate colonne2" = Table.ReorderColumns(#"Rinominate colonne2",{"COD PROD", "Collaboratore", "Regione", "Column6", "Categoria", "Prodotto", "Prezzo unitario", "Quantità"}),
    #"Rinominate colonne3" = Table.RenameColumns(#"Riordinate colonne2",{{"Column6", "Data"}}),
    #"Testo troncato" = Table.TransformColumns(#"Rinominate colonne3",{{"Collaboratore", Text.Trim, type text}}),
    #"Filtrate righe3" = Table.SelectRows(#"Testo troncato", each true),
    #"Testo troncato1" = Table.TransformColumns(#"Filtrate righe3",{{"COD PROD", Text.Trim, type text}}),
    #"Sostituito valore3" = Table.ReplaceValue(#"Testo troncato1","Emilia.Romagna","Emilia Romagna",Replacer.ReplaceText,{"Regione"}),
    #"Sostituito valore4" = Table.ReplaceValue(#"Sostituito valore3","Emilia-Romagna","Emilia Romagna",Replacer.ReplaceText,{"Regione"}),
    #"Aggiunta colonna personalizzata" = Table.AddColumn(#"Sostituito valore4", "TOTALE", each [Prezzo unitario]*[Quantità]),
    #"Rinominate colonne4" = Table.RenameColumns(#"Aggiunta colonna personalizzata",{{"Data", "Data Ordine"}}),
    #"Ordinate righe1" = Table.Sort(#"Rinominate colonne4",{{"Collaboratore", Order.Ascending}}),
    #"Intervallo testo inserito" = Table.AddColumn(#"Ordinate righe1", "Intervallo testo", each Text.Middle([COD PROD], 2, 4), type text),
    #"Rimosse colonne6" = Table.RemoveColumns(#"Intervallo testo inserito",{"Intervallo testo"}),
    #"Caratteri finali inseriti" = Table.AddColumn(#"Rimosse colonne6", "Caratteri finali", each Text.End([COD PROD], 4), type text),
    #"Filtrate righe4" = Table.SelectRows(#"Caratteri finali inseriti", each ([Collaboratore] <> "Fove Anna")),
    #"Aggiunta colonna personalizzata1" = Table.AddColumn(#"Filtrate righe4", "IVA", each [TOTALE]*0.22),
    #"Modificato tipo3" = Table.TransformColumnTypes(#"Aggiunta colonna personalizzata1",{{"IVA", Currency.Type}}),
    #"CREO colonna CATPROD" = Table.CombineColumns(#"Modificato tipo3",{"Categoria", "Prodotto"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"CATPROD"),
    #"Colonna condizionale aggiunta" = Table.AddColumn(#"CREO colonna CATPROD", "SE", each if [Quantità] > 20 then "TROVATO" else null),
    #"Sostituito valore5" = Table.ReplaceValue(#"Colonna condizionale aggiunta",null,"NON TROVATO",Replacer.ReplaceValue,{"SE"}),
    #"Trasformo la regione in MAIUSCOLO" = Table.TransformColumns(#"Sostituito valore5",{{"Regione", Text.Upper, type text}})
in
    #"Trasformo la regione in MAIUSCOLO"